name = "Silver Lining"
author = "omo50, Adrenix, BlueStaggo, icanttellyou"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bac9d37a22743e71e06d60a5a5c81d41d57c2eca9bfddfd0aaba24c571d01c19"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.206"
