name = "Silver Lining"
author = "omo50, Adrenix, BlueStaggo, icanttellyou"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd60c9bb93f0105e3f748bf133ba0ab1bec3381cb94f378e57e2bf829a5be33a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
