[General]
	#Allows a player to teleport to a located biome when in creative mode, opped, or in cheat mode.
	allowTeleport = true
	#Allows players to view the precise coordinates and distance of a located structure on the HUD, rather than relying on the direction the compass is pointing.
	displayCoordinates = true
	#biomeSize * radiusModifier = maxSearchRadius. Raising this value will increase search accuracy but will potentially make the process more resource .
	# Default: 2500
	# Range: 0 ~ 1000000
	radiusModifier = 2500
	#biomeSize * sampleSpaceModifier = sampleSpace. Lowering this value will increase search accuracy but will make the process more resource intensive.
	# Default: 16
	# Range: 0 ~ 1000000
	sampleSpaceModifier = 16
	#A list of biomes that the compass will not be able to search for, specified by resource location. The wildcard character * can be used to match any number of characters, and ? can be used to match one character. Ex: ["minecraft:savanna", "minecraft:desert", "minecraft:*ocean*"]
	biomeBlacklist = [
		"blueprint:original_source_marker",
		"minecraft:bamboo_jungle",
		"minecraft:cold_ocean",
		"minecraft:dark_forest",
		"minecraft:deep*ocean",
		"minecraft:deep_dark",
		"minecraft:dripstone_caves",
		"minecraft:flower_forest",
		"minecraft:frozen_ocean",
		"minecraft:frozen_peaks",
		"minecraft:grove",
		"minecraft:ice_spikes",
		"minecraft:jagged_peaks",
		"minecraft:lukewarm_ocean",
		"minecraft:lush_caves",
		"minecraft:mangrove_swamp",
		"minecraft:old_growth_birch_forest",
		"minecraft:old_growth_pine_taiga",
		"minecraft:old_growth_spruce_taiga",
		"minecraft:snowy_beach",
		"minecraft:snowy_slopes",
		"minecraft:stony_peeks",
		"minecraft:sunflower_plains",
		"minecraft:warm_ocean",
		"minecraft:windswept_gravelly_hills",
		"minecraft:windswept_savanna",
		"moderner_beta:*",
		"terrestria:caldera",
		"terrestria:hemlock_treeline",
		"terrestria:japanese_maple_forest",
		"terrestria:sakura_forest",
		"terrestria:windswept_redwood_forest",
		"traverse:autumnal_woods",
		"traverse:coniferous_forest",
		"traverse:snowy_coniferous_forest"
	]
	#The maximum number of samples to be taken when searching for a biome.
	# Default: 50000
	# Range: 0 ~ 1000000
	maxSamples = 50000
